### ISSUE TITLE
Mobile Notification Attachment 

### ISSUE THREAD

**Issue by robinfdx** [thiagomdiniz/zabbix-google-chat#1]
Hello,

Thanks for your work Thiago ! Do you have any tips for the mobile notification, currently i've this message 
"Monitoring Zabbix : sent you an attachment  "

With my rocketchat connector i can send object directly in the notification, but i didn't find with Google Chat, do you have any idea ?

**Comment by thiagomdiniz** [comment]
Hi @robinfdx , thanks!
do you mean that when you try to read the same message you read on your computer but in your mobile, the mobile app fails to show the message?
Do you still notice this error? I don't found any reference to this error.
