### ISSUE TITLE
Resolvido - usando python3.9 peguei o erro KeyError: '"https'

### ISSUE THREAD

**Issue by mtllc22** [thiagomdiniz/zabbix-google-chat#10]
só substituir
na linha 211 e 212

faz requisicao http na API
        http_obj = Http()
        response = http_obj.request(
por
faz requisicao http na API
        http_obj = httplib2.Http()
        response, content = http_obj.request(

e importar import httplib2

**Comment by thiagomdiniz** [comment]
Olá @mtllc22 , obrigado pela informação!

Gostaria de avisar que estou descontinuando este repo. Se você utiliza o Zabbix na versão 5.0 ou superior, teste usar a nova versão que disponibilizei:
https://github.com/thiagomdiniz/zabbix-google-chat-webhook
