### ISSUE TITLE
Widget notificação

### ISSUE THREAD

**Issue by sudo-bruno** [thiagomdiniz/zabbix-google-chat#11]
Olá Thiago, primeiramente parabéns pelo script, implementei em nosso servidor Zabbix e esta funcionando com perfeição.

Gostava apenas de tirar uma duvida, e talvez solucionar um probleminha que temos.
Quanto chega da notificação, não sabemos exatamente qual serviço/host gerou aquela notificação, 
no corpo da notificação aparece apenas as informações que mostro na imagem abaixo.

![Zabbix-GoogleChat](https://user-images.githubusercontent.com/6240550/234913594-ea757ac3-e01a-441a-b99c-47a3d26a1739.png)

Sei que "ZS Zabbix" é o nome que defini no webhook do Google Chat, mas "(App)" e "(Zabbix)" não encontro onde são definidos e se há possibilidade de capturar o host que gerou o evento, para assim, exibir logo na notificação.

Desde já, obrigado e mais uma vez parabéns

**Comment by thiagomdiniz** [comment]
Olá @fbrunosf , obrigado!
Realmente sua ideia faz sentido, seria legal ter um pedaço da mensagem já na notificação.

Eu fiz alguns testes e obtive o mesmo comportamento:

Chrome:
![image](https://github.com/thiagomdiniz/zabbix-google-chat/assets/29825093/15eca79a-8c8c-497e-9c2b-2f141aedf8e0)

Firefox:
![image](https://github.com/thiagomdiniz/zabbix-google-chat/assets/29825093/95e278af-bcb1-4249-bb70-3519cd0b0109)


Eu acredito que isso seja um padrão/limitação desse recurso de notificação dele (ou do navegador?).
Procurei algum meio de customizar este pop-up de notificação que ele gera, encontrei artigos como este abaixo, mas nada relacionado a customização do que é exibido na notificação.
https://support.google.com/chat/answer/7655718?ref_topic=7649115#zippy=


Pelo que vi também não há um aplicativo/instalador do Google Chat, ele instala pelo navegador mesmo (PWA):
https://support.google.com/chat/answer/9455386?hl=en

Então não vejo muita saída, a não ser que alguém desenvolva uma extensão para o navegador ou algo assim.
Se descobrir algo nos deixe saber.

Abraço!

**Comment by thiagomdiniz** [comment]
Olá novamente @fbrunosf , acho que me precipitei na resposta.

Fiz mais alguns testes aqui e o motivo de o pop-up de notificação não exibir nenhum texto é porque a mensagem enviada pelo script é `card-based`. Detalhes:
https://developers.google.com/chat/api/guides/message-formats/cards

Ao alterar o script para enviar uma mensagem de "texto puro", a notificação realmente consegue exibir o texto mensagem:

![image](https://github.com/thiagomdiniz/zabbix-google-chat/assets/29825093/046b32ae-7ddf-4a1e-95fb-8c7d23e4a0b8)

Detalhes da mensagem em texto puro:
https://developers.google.com/chat/api/guides/message-formats/text

Em breve devo lançar uma nova versão que não vai precisar de python/script externo, usando a funcionalidade de webhook do Zabbix.
Tentarei implementar a opção de enviar a mensagem como card ou como texto, para que o usuário possa escolher.

Obrigado!
