### ISSUE TITLE
Failure with TRIGGER.ID in event[0]

### ISSUE THREAD

**Issue by b1tsh1ft3r** [thiagomdiniz/zabbix-google-chat#2]
After setting this up step by step i am able to send test nofitications manually, however when triggered with real data it appears to fail with the following. 

Traceback (most recent call last):
File "/etc/zabbix/alertscripts/google_chat.py", line 244, in <module>
cs.sendMessage(event)
File "/etc/zabbix/alertscripts/google_chat.py", line 197, in sendMessage
if self.trigger_id in self.evt_thread:
AttributeError: ChatSender instance has no attribute 'trigger_id'

Using zabbix 4.2.1

**Comment by b1tsh1ft3r** [comment]
Typo on my part :) Works as intended

**Comment by jtoscano-twks** [comment]
Hi @b1tsh1ft3r, I have the same problem. Can you guide me please around it?

**Comment by b1tsh1ft3r** [comment]
> Hi @b1tsh1ft3r, I have the same problem. Can you guide me please around it?
@jonathan464

The example default message format for the operations/recovery operations/update operations tabs in the configurations > actions > hangouts action itself are not really explained correctly and or i guess typed out correctly in the guide it seems. 

Im using the following with success on zabbix 4.2.6

0#{EVENT.TIME}#{EVENT.DATE}#{TRIGGER.NAME}#{HOST.NAME}#{TRIGGER.SEVERITY}#{EVENT.ID}#{TRIGGER.URL}#{TRIGGER.ID}#- {HOST.DESCRIPTION}

1#{EVENT.RECOVERY.TIME}#{EVENT.RECOVERY.DATE}#{TRIGGER.NAME}#{HOST.NAME}#{TRIGGER.SEVERITY}#{EVENT.ID}#{TRIGGER.URL}#{TRIGGER .ID}#- {HOST.DESCRIPTION}

2#{ACK.TIME}#{ACK.DATE}#{USER.FULLNAME}#{ACK.MESSAGE}#{EVENT.STATUS}#{EVENT.ID}#{TRIGGER.ID}

Hopefully this helps!

**Comment by jtoscano-twks** [comment]
Thanks for your suggestion @b1tsh1ft3r, however I'm still fighting with this problem. What is the python version you are using? I'm using 2.7.5.

**Comment by vandersonpsilva** [comment]
Hi, did anyone manage to fix this problem?
