### ISSUE TITLE
[Zabbix issue]

### ISSUE THREAD

**Issue by jtoscano-twks** [thiagomdiniz/zabbix-google-chat#3]
Hi @thiagomdiniz 

Did you face this issue when you try to send the message? I have this warning:
Traceback (most recent call last):
File “/usr/lib/zabbix/alertscripts/google_chat.py”, line 245, in <module>
cs.sendMessage(event)
File “/usr/lib/zabbix/alertscripts/google_chat.py”, line 198, in sendMessage
if self.trigger_id in self.evt_thread:
AttributeError: ChatSender instance has no attribute ‘trigger_id’
Can you help me please?

Thanks,

**Comment by dark4rest** [comment]
Traceback (most recent call last):
  File "./google_chat.py", line 243, in <module>
    cs = ChatSender(webhook_name)
  File "./google_chat.py", line 51, in __init__
    with open(self.datafile, 'w') as f:
AttributeError: ChatSender instance has no attribute 'datafile'

**Comment by prjoni99** [comment]
Has anyone been able to figure this one out? I'm stuck in the same message and this looks so good!! Thanks!

**Comment by vandersonpsilva** [comment]
Hi, did anyone manage to fix this problem?

**Comment by thiagomdiniz** [comment]
Hi @dark4rest ,
this error is probably because the `INI_FILE` path is wrong in your `google_chat.py` script. This path should point to the `google_chat.ini` file.
Can you verify this?

The `google_chat.py` script also needs read/write permissions on `eventsthreads.json` (the datafile parameter on google_chat.ini).

**Comment by thiagomdiniz** [comment]
Hi @jonathan464 ,
I couldn't replicate this error. Can you give more details of your environment? (python version and zabbix action messages you're using).

Hi @prjoni99 and @vandersonpsilva , if your error is the same as @dark4rest , see my [previous comment](https://github.com/thiagomdiniz/zabbix-google-chat/issues/3#issuecomment-1203458918). If not, please provide more details of your environment such as the python version and zabbix action messages you're using.
Look at [this comment](https://github.com/thiagomdiniz/zabbix-google-chat/issues/2#issuecomment-532339609) too.

**Comment by evandroteixeira1710** [comment]
Boa tarde Thiago, 
cara eu tive um  problema similar do colega acima...
segui passo a passo conforme a sua documentação.
Até pensei que fosse algum parametro referente ao zabbix e fui comparar o que temos que envia mensagem para o rocketchat.
o erro é :

 Traceback (most recent call last):
  File "google_chat.py", line 245, in <module>
    cs.sendMessage(event)
  File "google_chat.py", line 76, in sendMessage
    date = event[2]
IndexError: list index out of range

**Comment by thiagomdiniz** [comment]
> Boa tarde Thiago, cara eu tive um problema similar do colega acima... segui passo a passo conforme a sua documentação. Até pensei que fosse algum parametro referente ao zabbix e fui comparar o que temos que envia mensagem para o rocketchat. o erro é :
> 
> Traceback (most recent call last): File "google_chat.py", line 245, in cs.sendMessage(event) File "google_chat.py", line 76, in sendMessage date = event[2] IndexError: list index out of range

Olá @evandroteixeira1710 ,
o seu erro parece algo com o conteúdo da mensagem configurada na ação. Consegues dar uma verificada e me retornar? Conforme documentação a mensagem fica algo como isso, cada campo separado por "#":
`0#{EVENT.TIME}#{EVENT.DATE}#{TRIGGER.NAME}#{HOST.NAME}#{TRIGGER.SEVERITY}#{EVENT.ID}#{TRIGGER.URL}#{TRIGGER.ID}#- {HOST.DESCRIPTION}`

Caso esteja tudo certo e o erro persista, me diga qual a versão do Python está utilizando e copie/cole o conteúdo das mensagens configuradas na ação.

Obrigado!

**Comment by thiagomdiniz** [comment]
Just wanted to let you know that I'm discontinuing this repo. If you use Zabbix version 5.0 or higher, test using the new version I made available:
https://github.com/thiagomdiniz/zabbix-google-chat-webhook

Thanks!
