### ISSUE TITLE
Issue with sending messages

### ISSUE THREAD

**Issue by ghost** [thiagomdiniz/zabbix-google-chat#4]
Ei, não tenho certeza se você ainda está lidando com problemas de suporte, mas estou tendo um problema ao enviar mensagens. Ao atingir a etapa de validação de saúde da sua publicação no medium.com, recebo o seguinte erro:

Traceback (most recent call last):
  File "./google_chat.py", line 244, in <module>
    cs.sendMessage(event)
  File "./google_chat.py", line 74, in sendMessage
    time = event[1]
IndexError: list index out of range

Até agora, verifiquei todas as minhas configurações, mas ainda não encontrei o problema, qualquer ajuda seria apreciada.

--------

Hey, not sure if you're still handling any support issues, but I'm having an issue with sending messages. When reaching the validating Health step of your medium.com post, I get the following error:

Traceback (most recent call last):
  File "./google_chat.py", line 244, in <module>
    cs.sendMessage(event)
  File "./google_chat.py", line 74, in sendMessage
    time = event[1]
IndexError: list index out of range

I've double checked all my settings thus far but I have yet to find the issue, any help would be appreciated.

**Comment by ghost** [comment]
nevermind, I figured it out, it was due to spacing.

**Comment by prjoni99** [comment]
Hey, where did you have the spacing issue? I'm having the same error.
Thanks!

**Comment by Egovican** [comment]
![image](https://user-images.githubusercontent.com/66505788/176794888-f7bea48a-7e04-4a2d-8206-8e66c816146c.png)
 When I adjust the order, there is no error.

**Comment by thiagomdiniz** [comment]
@prjoni99 check [this comment](https://github.com/thiagomdiniz/zabbix-google-chat/issues/2#issuecomment-532339609).
