### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by brosig** [thiagomdiniz/zabbix-google-chat#5]
Quando simulo um erro pra testar o envio, recebo esse alerta:

```
Traceback (most recent call last):
File "/usr/lib/zabbix/alertscripts/google_chat.py", line 3, in <module>
from httplib2 import Http
ImportError: No module named httplib2
```

Mas eu instalei as dependências.
Não consegui rastrear o motivo. Alguém tem alguma idéia?

Grato

Edit:
Ao instalar as dependências deveria ter instalado com o usuário que executa o processo do Zabbix (no meu caso `sudo`) e não o usuário `Zabbix`.

Mesmo assim deu erro. 
No meu caso foi uma série de fatores:
- Espaços nas mensagens padrão (tirei todos os espaços)
- Erro de digitação no Media Type

Sugestão pra quem tiver problemas:
- Leia e releia tudo que digitou (no script e no Zabbix)
- Leia a documentação (https://www.zabbix.com/documentation/3.2/manual/config/notifications/media/script)

Pra mim ainda ficou um problema que não sei se é erro ou funcionalidade:
Ao enviar uma notificação, no Chats as mensagens ficam agrupadas por tipo (erro, recuperação, reconhecimento). Acho que seria mais lógico ficar agrupado por Incidente.

**Comment by thiagomdiniz** [comment]
Olá @brosig ,
conforme o tópico `Validando o funcionamento` [deste artigo](https://medium.com/monitoracaodeti/enviando-notifica%C3%A7%C3%B5es-do-zabbix-via-api-do-hangouts-chat-aa0c0e8197a1) as mensagens devem ficar agrupadas por conversa.
O script agrupa pelo ID da trigger, controlando isso mediante registro no arquivo `eventsthreads.json`. Verifique se o arquivo `eventsthreads.json` existe, se o script está com permissão para escrever nele e se o caminho dele está correto `google_chat.ini`.
