### ISSUE TITLE
How to setup different triggers to different room?

### ISSUE THREAD

**Issue by akong77** [thiagomdiniz/zabbix-google-chat#6]
I has set two rooms.example room a and room b.
I want set some triggers send message to room a and other triggers send to room b.Could I to do this?And how to do it?
Thanks a lot.

**Comment by thiagomdiniz** [comment]
Hi @akong77 ,
in the `chat` section of your `google_chat.ini` you'll define the two rooms, like this:
```
[chat]
RoomA = webhook_url_generated_in_hangouts_chat_room
RoomB = webhook_url_generated_in_hangouts_chat_room
```

Next, you'll create one user for each room and add the `Google Chat Room` media type to them. In the field `Send to` you define the name of the room (RoomA or RoomB).
So, in your actions, you can choose for which user to send the notification.
