### ISSUE TITLE
URL defaults to HTTPS

### ISSUE THREAD

**Issue by FCP-MattIT** [thiagomdiniz/zabbix-google-chat#8]
Our server is internal only and we want to pass http thru the URL. It's set in the .ini but the 'view in zabbix' button forces https.

**Comment by thiagomdiniz** [comment]
Hi @FCP-MattIT ,
from what i understand this is a default google chat security behavior. Does not allow the use of insecure URLs.

As a workaround we can use a secure redirection service such as "https://httpbin.org/redirect-to?url=" or "https://www.google.com/url?q=".

I applied [these changes](https://github.com/thiagomdiniz/zabbix-google-chat/commit/6ede7766485f2c9b1162256c0380a5621e17060b) to make this URL handling in the code (tested with python3).
Could you test with this [new version of the file](https://github.com/thiagomdiniz/zabbix-google-chat/blob/8-url-defaults-to-https/google_chat.py)?
